
CREATE TABLE B2W_CKT_FR_DAYS (
	REGION_CODE VARCHAR2(20), 
	INITIAL_WEIGHT NUMBER,   
	FINAL_WEIGHT NUMBER, 
	WAREHOUSE_ID NUMBER,  
	CONTRACT_TYPE VARCHAR2(5), 
	PROMOTION_TYPE VARCHAR2(20), 
	PERIOD CHAR(1),  
	LOGISTIC_CONTRACT VARCHAR2(20), 
	DAYS NUMBER, 
	PRICE NUMBER,
	SPECIAL_DELIVERY CHAR(1 BYTE),
	HR_CORTE NUMBER(2)
);


CREATE TABLE B2W_CKT_FR_REGION (
	REGION_CODE VARCHAR2(20), 
	POSTAL_CODE_START NUMBER,   
	POSTAL_CODE_END NUMBER
);

CREATE TABLE B2W_CKT_FR_PRICE (
	REGION_CODE VARCHAR2(20), 
	INITIAL_WEIGHT NUMBER,
	FINAL_WEIGHT NUMBER,
	WAREHOUSE_ID NUMBER,
	CONTRACT_TYPE VARCHAR2(5),
	VL_FREIGHT NUMBER
);

CREATE TABLE NATIONAL_FREIGHT  ( 
  INITIAL_WEIGHT     NUMBER NULL,
  FINAL_WEIGHT       NUMBER NULL,
  PRICE              NUMBER NULL,
  MULTIPLIER_TYPE    VARCHAR2(20) NULL,
  POSTAL_CODE_START  NUMBER NULL,
  POSTAL_CODE_END    NUMBER NULL,
  CARRIER_CNPJ       VARCHAR2(20) NULL,
  CONTRACT_TYPE  VARCHAR2(20) NULL,
  DAYS               NUMBER NULL,
  ACCESSORIAL_COST   NUMBER NULL,
  SUFRAMA            CHAR(1) NULL,
  WAREHOUSE_ID       NUMBER NULL 
);
